name: camera_android_camerax
description: Android implementation of the camera plugin using the CameraX library.
repository: https://github.com/flutter/packages/tree/main/packages/camera/camera_android_camerax
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+camera%22
version: 0.5.0+18
publish_to: none

environment:
  sdk: ">=2.19.0 <4.0.0"

flutter:
  plugin:
    implements: camera
    platforms:
      android:
        package: io.flutter.plugins.camerax
        pluginClass: CameraAndroidCameraxPlugin
        dartPluginClass: AndroidCameraCameraX

dependencies:
  async:
  camera_platform_interface:
    path: ../camera_platform_interface
  flutter:
    sdk: flutter
  integration_test:
    sdk: flutter
  meta: 
  stream_transform: 

dev_dependencies:
  build_runner: 
  flutter_test:
    sdk: flutter
  mockito:
  pigeon: 

topics:
  - camera
