name: camera_platform_interface
description: A common platform interface for the camera plugin.
repository: https://github.com/flutter/packages/tree/main/packages/camera/camera_platform_interface
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+camera%22
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 2.5.2

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  cross_file:
  flutter:
    sdk: flutter
  plugin_platform_interface:
  stream_transform:

dev_dependencies:
  async:
  flutter_test:
    sdk: flutter

topics:
  - camera
