name: camera
description: A Flutter plugin for controlling the camera. Supports previewing
  the camera feed, capturing images and video, and streaming image buffers to
  Dart.
repository: https://github.com/flutter/packages/tree/main/packages/camera/camera
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+camera%22
version: 0.10.5+4
publish_to: none

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: camera_android
      ios:
        default_package: camera_avfoundation

dependencies:
  camera_android_camerax:
    path: ../camera_android_camerax
  camera_avfoundation: 
    path: ../camera_avfoundation
  camera_platform_interface:
    path: ../camera_platform_interface
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: 
  quiver: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 
  plugin_platform_interface: 
  video_player:

topics:
  - camera
